package com.struxo.kit.core.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.struxo.kit.core.data.local.dao.AuthUserDao
import com.struxo.kit.core.data.local.entity.AuthUserEntity

/**
 * Room Multiplatform database for Struxo.
 *
 * Platform-specific builders are in `androidMain` and `iosMain`.
 * The [AppDatabaseConstructor] expect/actual is auto-generated by the Room KSP compiler.
 */
@Database(entities = [AuthUserEntity::class], version = 1)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    /** DAO for authenticated user cache operations. */
    abstract fun authUserDao(): AuthUserDao

    companion object {
        const val DB_NAME = "struxo.db"
    }
}

/**
 * Room KSP generates the `actual` implementations for each platform target.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>
